WebApplication2/Controllers/BaseController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebApplication2.Controllers
{
    public class BaseController : Controller
    {
        [Route("/")]
        public IActionResult Index()
        {
            return View("Views/Index.cshtml");
        }
        [Route("Dupes")]
        public IActionResult Dupe()
        {
            return View("views/DupeFinder.cshtml");
        }

        [Route("/Dupes/find")]
        public ViewResult Dupes(string STR1,string STR2,string delim)
        {
            ViewBag.Head = DupeFinder.Find(STR1, STR2, delim);
            return View("~/Views/DupeFinderResult.cshtml");
        }
    }
}

WebApplication2/Views/DupeFinder.cshtml
@{
    ViewData["Title"] = "DupeFinder";
}

    <h2>Поиск дублей</h2>
<head>
    <title>Поиск дублей</title>
</head>
<body>
    @using (Html.BeginForm("Dupes", "Base"))
    {
        <body>
            Первая строка:
            <p></p>
            @Html.TextArea("STR1")
            <p></p>
            Вторая строка:
            <p></p>
            @Html.TextArea("STR2")
            <p></p>
            Разделитель:
            <p></p>
        </body>
        @Html.TextBox("delim")
        <input type="submit" name="send" value="Найти дубли">
    }

</body>

WebApplication2/Views/DupeFinderResult.cshtml
@{
    ViewData["Title"] = "DupeFinderResult";
}
<html>
<head>
    <title>Результат поиска</title>
</head>
    <body>
        <h1>
            Результат поиска
        </h1>
        @Html.Raw(ViewBag.Head)

    </body>
</html>
    

WebApplication2/Views/Index.cshtml
@{
    ViewData["Title"] = "Index";
}
    <h2>Утилиты</h2>
<head>
    <title>
        Утилиты
    </title>
</head>
<body>
    <a href="/Dupes">Поиск дублей</a>
</body>